<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="324106" started-at="2017-05-01T03:46:58Z" finished-at="2017-05-01T03:52:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="324106" started-at="2017-05-01T03:46:58Z" finished-at="2017-05-01T03:52:22Z">
      <class name="psbankTestCases.PSBankTestCases">
        <test-method status="PASS" signature="runSecurity()[pri:0, instance:psbankTestCases.PSBankTestCases@15d3402]" name="runSecurity" is-config="true" duration-ms="369" started-at="2017-05-01T11:46:57Z" finished-at="2017-05-01T11:46:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runSecurity -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:psbankTestCases.PSBankTestCases@15d3402]" name="launchBrowser" is-config="true" duration-ms="61221" started-at="2017-05-01T11:46:58Z" finished-at="2017-05-01T11:47:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="IncorrectAccountName()[pri:0, instance:psbankTestCases.PSBankTestCases@15d3402]" name="IncorrectAccountName" duration-ms="15006" started-at="2017-05-01T11:47:59Z" finished-at="2017-05-01T11:48:14Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at psbankTestCases.PSBankGenericScript.ExecuteScript(PSBankGenericScript.java:25)
	at psbankTestCases.PSBankTestCases.IncorrectAccountName(PSBankTestCases.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IncorrectAccountName -->
        <test-method status="FAIL" signature="IncorrectAccountNumber()[pri:1, instance:psbankTestCases.PSBankTestCases@15d3402]" name="IncorrectAccountNumber" duration-ms="60" started-at="2017-05-01T11:48:14Z" finished-at="2017-05-01T11:48:14Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at psbankTestCases.PSBankGenericScript.ExecuteScript(PSBankGenericScript.java:25)
	at psbankTestCases.PSBankTestCases.IncorrectAccountNumber(PSBankTestCases.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- IncorrectAccountNumber -->
        <test-method status="PASS" signature="AutoLoanCalc()[pri:2, instance:psbankTestCases.PSBankTestCases@15d3402]" name="AutoLoanCalc" duration-ms="139343" started-at="2017-05-01T11:48:14Z" finished-at="2017-05-01T11:50:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AutoLoanCalc -->
        <test-method status="PASS" signature="HomeLoanCalc()[pri:3, instance:psbankTestCases.PSBankTestCases@15d3402]" name="HomeLoanCalc" duration-ms="108179" started-at="2017-05-01T11:50:34Z" finished-at="2017-05-01T11:52:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HomeLoanCalc -->
        <test-method status="PASS" signature="terminateBrowser()[pri:0, instance:psbankTestCases.PSBankTestCases@15d3402]" name="terminateBrowser" is-config="true" duration-ms="2105" started-at="2017-05-01T11:52:22Z" finished-at="2017-05-01T11:52:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- terminateBrowser -->
      </class> <!-- psbankTestCases.PSBankTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
